### ISSUE TITLE
Build runs out of memory

### ISSUE THREAD

**Issue by MmtBkn** [simonhaenisch/rollup-plugin-typescript-paths#6]
Hello,

We added this plugin to properly resolve paths. However, the build takes forever, and eventually runs out of memory, and crashes. Our build is very small and takes couple of seconds if we don't use this plugin. Any ideas what could cause this?

**Comment by simonhaenisch** [comment]
Hm, could be a circular dependency? The source of this plugin is very small so maybe you can figure it out with some console logs.

https://github.com/simonhaenisch/rollup-plugin-typescript-paths/blob/3f93159a99d990466034b3a2148e7231c8002cc3/index.ts#L14-L50

Other than that I don't have an idea what it could be, I haven't used this plugin myself in a long while.

**Comment by MmtBkn** [comment]
Thank you @simonhaenisch for the answer. We did debug the code, and it seems like It's not able to resolve final build file. It's resolving d.ts instead, and keep retrying to find the build file. We've added the `tsConfigPath: 'tsconfig.base.json'` and added path to the build file (full path to js file), and it worked.

**Comment by simonhaenisch** [comment]
That's weird, `nodeModuleNameResolver` should not resolve to `.d.ts` if there's also a `.ts` or `.js` file with the same name in the same directory. But it's up to `nodeModuleNameResolver` I guess, which is a TypeScript API.

Anyway, if this plugin does resolve to a `.d.ts` file, it returns `null` (see line 35 above), meaning it won't resolve the import, and leave it up to rollup/other plugins to do that.

Glad you figured out a solution though.
