### ISSUE TITLE
should strip comments from `tsconfig.json` before `JSON.parse()`

### ISSUE THREAD

**Issue by beeplin** [simonhaenisch/rollup-plugin-typescript-paths#7]
`tsconfig.json` allows comments in JSON.

**Comment by beeplin** [comment]
can be simply done via https://github.com/sindresorhus/strip-json-comments

**Comment by simonhaenisch** [comment]
Thanks for the issue. Would be helpful if you were a bit more clear about the actual problem next time, like "this plugin breaks when I have a comment in my tsconfig ...". 🙃 I didn't go with your proposed solution because the TypeScript API has this built-in.
